# Meta Data for SEO

## Homepage
title = "Filecoin Docs"
titleSeparator = "-"
titleAddition = "Home"
description = "Documentation for Filecoin - A decentralized storage network for humanity's most important information."
useLogo = true

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["/logos/Filecoin-logo-blue+black.png"]
ogLocale = "en_US"
domainTLD = "docs.filecoin.io"
titleHome = "Filecoin Docs"

## Twitter Cards
twitterSite = "@filecoin"
twitterCreator = "@protocollabs"

## JSON-LD
schemaType = "Organization"
schemaName = "Filecoin"
schemaAuthor = "Protocol Labs"
schemaAuthorTwitter = "https://twitter.com/filecoin"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/filecoin/"
schemaAuthorGitHub = "https://github.com/filecoin-project"
schemaLocale = "en-US"
schemaLogo = "filecoin.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "filecoin.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/filecoin"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/filecoin-project/filecoin-docs"
schemaSection = "blog"


## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = "Built by Protocol Labs"
footer_link = "https://protocol.ai"

# Feed
copyRight = ""

# Alert
alert = true
alertDismissable = true
alertText = "Want to help us test out the Filecoin Virtual Machine? <br>Check out the <a href='https://spacewarp.fvm.dev/'>FVM Space Warp Hackathon</a> starting January 20th!"

# Edit Page
repoHost = "GitHub"
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ]
docsRepo = "https://github.com/filecoin-project/filecoin-docs"
docsRepoBranch = "main"
docsRepoSubPath = ""
editPage = true
lastMod = false

[sections]
#  sectionNav = ["docs", "blog"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = "ALL"
  searchSectionsIndex = ["about", "blog", "build", "developers", "fvm", "get-started", "networks", "reference", "storage-provider", "store"]
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false
  navbarSticky = true
  toTopButton = false
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1
  progressBar = true


[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = false
